"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AnimatePresence, MotionConfig, motion } from "framer-motion";

type Person = { id:number; name:string; title:string; rating:number; reviews:number; experience:string; tags:string[]; photo:string; availability:string };
type RequestItem = { id:number; title:string; description:string; status:string; created_at:string; replies:number };
type Appointment = { id:number; psychologist_id:number; psychologist:string; title:string; photo:string; date:string; time:string; topic:string; mode:string; status:string };
type MessageItem = { id:number; psychologist_id:number; psychologist:string; photo:string; body:string; mine:number; created_at:string; read:number };
type Resource = { id:number; title:string; category:string; read_time:string; color:string; icon:string; description:string };
type Data = { psychologists:Person[]; requests:RequestItem[]; appointments:Appointment[]; messages:MessageItem[]; resources:Resource[]; profile:{name:string;email:string} };

const iconPaths: Record<string,string> = {
  home:"M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z",
  search:"M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4ZM16 16l4.3 4.3",
  request:"M4 5.5h16v11H9l-5 3v-14Z M8 9h8M8 13h5",
  calendar:"M5 4.5h14a1.5 1.5 0 0 1 1.5 1.5v13H3.5V6A1.5 1.5 0 0 1 5 4.5ZM7.5 3v3M16.5 3v3M4 9h16",
  messages:"M4 5h16v11H9l-5 3V5ZM8 9h8M8 12.5h5",
  resource:"M5 4h13a1 1 0 0 1 1 1v15H6a2 2 0 0 1-2-2V5a1 1 0 0 1 1-1ZM7 4v16M10 8h6M10 11h5",
  community:"M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM16 11a2.5 2.5 0 1 0 0-5M3 19c.2-3 2.1-4.5 5-4.5s4.8 1.5 5 4.5ZM14 15c3.7-.5 6.5 1 7 4",
  info:"M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM12 11v5M12 8h.01",
  bell:"M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4",
  heart:"M20.5 8.8c0 4.4-8.5 10-8.5 10s-8.5-5.6-8.5-10a4.5 4.5 0 0 1 8.5-2 4.5 4.5 0 0 1 8.5 2Z",
  person:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21c.3-4.2 3.2-6.5 8-6.5s7.7 2.3 8 6.5",
  cloud:"M7 18h10a4 4 0 0 0 .2-8 5.4 5.4 0 0 0-10.4-1A4.5 4.5 0 0 0 7 18Z",
  leaf:"M20 4C10 4 4 8 4 14a6 6 0 0 0 6 6c6 0 10-7 10-16ZM4 20l9-9",
  pulse:"M3 12h4l2-5 4 10 2-5h6",
  lifebuoy:"M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM8.2 8.2l-3-3M15.8 8.2l3-3M8.2 15.8l-3 3M15.8 15.8l3 3M9 9l6 6M15 9l-6 6",
  sparkle:"m12 3 1.8 6.2L20 11l-6.2 1.8L12 19l-1.8-6.2L4 11l6.2-1.8L12 3ZM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8L19 16Z",
  clock:"M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM12 7v5l3.5 2",
  video:"M4 7h11a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2ZM17 10l5-3v10l-5-3",
  send:"m22 2-7 20-4-9-9-4 20-7ZM22 2 11 13",
  arrow:"M4 12h15M13 5l7 7-7 7",
  plus:"M12 5v14M5 12h14"
};
function DropIcon({name,className="",filled=false}:{name:string;className?:string;filled?:boolean}) {
  return <span className={`drop-icon ${className}`} aria-hidden="true"><svg viewBox="0 0 24 24" fill={filled?"currentColor":"none"} stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round"><path d={iconPaths[name]??iconPaths.sparkle}/></svg></span>;
}
const specialtyIcons = ["pulse","heart","person","cloud","leaf","lifebuoy"];
const specialties = ["Тревога и стресс","Отношения","Самооценка","Депрессия и апатия","Потеря смысла","Кризисные ситуации"];
const menus = [["home","Главная","home"],["psychologists","Подобрать психолога","search"],["requests","Мои обращения","request"],["sessions","Мои сессии","calendar"],["messages","Сообщения","messages"],["resources","Полезное","resource"],["community","Сообщество","community"],["about","О сервисе","info"]];
const initial:Data = { psychologists:[],requests:[],appointments:[],messages:[],resources:[],profile:{name:"Алексей",email:""} };
const fmtDate = (d:string) => { const date=new Date(`${d}T12:00:00`); return new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long"}).format(date); };

export default function Home() {
  const [data,setData]=useState<Data>(initial); const [section,setSection]=useState("home"); const [loading,setLoading]=useState(true);
  const [query,setQuery]=useState(""); const [specialty,setSpecialty]=useState(""); const [favorites,setFavorites]=useState<number[]>([]); const [chosen,setChosen]=useState<number|null>(null);
  const [modal,setModal]=useState<"request"|"booking"|"profile"|null>(null); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [conversation,setConversation]=useState<number|null>(null); const [chatText,setChatText]=useState(""); const [resource,setResource]=useState<Resource|null>(null); const [filter,setFilter]=useState("Предстоящие");

  async function refresh(){ const r=await fetch("/api/data"); if(r.ok)setData(await r.json()); setLoading(false); }
  useEffect(()=>{ refresh().catch(()=>setLoading(false)); const saved=localStorage.getItem("mindplace-favorites"); if(saved)setFavorites(JSON.parse(saved)); },[]);
  const action=async(body:Record<string,unknown>,method="POST")=>{setBusy(true);try{const r=await fetch("/api/data",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error);setData(result);return true;}catch(e){setNotice(e instanceof Error?e.message:"Что-то пошло не так");return false;}finally{setBusy(false)}};
  const notify=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(""),2800)};
  const toggleFav=(id:number)=>setFavorites(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem("mindplace-favorites",JSON.stringify(next));return next;});
  const filteredPeople=useMemo(()=>data.psychologists.filter(p=>(!query||`${p.name} ${p.title} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(!specialty||(specialty==="Избранное"?favorites.includes(p.id):p.tags.some(t=>t.toLowerCase().includes(specialty.toLowerCase().split(" ")[0]))))),[data.psychologists,query,specialty,favorites]);
  const unread=data.messages.filter(m=>!m.mine&&!m.read).length;
  const selectedPerson=data.psychologists.find(p=>p.id===chosen)??data.psychologists[0];

  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let payload:Record<string,unknown>;
    if(modal==="request")payload={action:"request",title:f.get("title"),description:f.get("description")};
    else if(modal==="booking")payload={action:"book",psychologistId:Number(f.get("psychologistId")),date:f.get("date"),time:f.get("time"),topic:f.get("topic")};
    else payload={action:"profile",name:f.get("name"),email:f.get("email")};
    if(await action(payload)){setModal(null);notify(modal==="request"?"Обращение создано":modal==="booking"?"Вы записаны на сессию":"Профиль обновлён");}}
  async function sendMessage(e:FormEvent){e.preventDefault();if(!chatText.trim()||conversation===null)return;const ok=await action({action:"message",psychologistId:conversation,body:chatText});if(ok)setChatText("");}
  function openChat(id:number){setConversation(id);setSection("messages");action({action:"read-messages",psychologistId:id},"PATCH");}

  const avatar=(person:Pick<Person,"photo"> & Partial<Pick<Person,"name">>,size="avatar")=><img className={size} src={person.photo} alt={person.name??"Психолог"} />;
  const personCard=(p:Person)=><motion.article className="person-card" key={p.id} whileHover={{ y: -4, boxShadow: "0 14px 36px rgba(29,61,56,.12)" }} transition={{ type: "spring", stiffness: 280, damping: 26 }}><div className="person-photo-wrap">{avatar(p,"person-photo")}<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={`save ${favorites.includes(p.id)?"saved":""}`} onClick={()=>toggleFav(p.id)} aria-label="В избранное"><DropIcon name="heart" filled={favorites.includes(p.id)} className="heart-drop" /></motion.button></div><h3>{p.name}</h3><p className="muted small">{p.title}</p><div className="tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><div className="rating"><b>★</b> {p.rating.toFixed(1)} <span>({p.reviews} отзывов)</span></div><div className="online"><i/> Онлайн · {p.availability}</div><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary full" onClick={()=>{setChosen(p.id);setModal("booking")}}>Записаться</motion.button></motion.article>;
  const sectionTitle=menus.find(m=>m[0]===section)?.[1]??"Главная";

  return <MotionConfig reducedMotion="user"><main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span>◕</span><span>◕</span></div><div><strong>MindPlace</strong><small>Забота рядом</small></div></div>
      <nav>{menus.map(([id,label,icon])=><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={`nav-item ${section===id?"active":""}`} key={id} onClick={()=>{setSection(id);if(id!=="messages")setConversation(null)}}><DropIcon className="nav-icon" name={icon} />{label}{id==="messages"&&unread>0&&<b className="nav-badge">{unread}</b>}</motion.button>)}</nav>
      <div className="sidebar-note"><span className="leaf">❧</span><h3>Тебе не нужно справляться в одиночку</h3><p>Поддержка, понимание и профессиональная помощь — ближе, чем кажется.</p><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary full" onClick={()=>setModal("request")}>Написать обращение</motion.button></div>
    </aside>
    <section className="main-area"><header className="topbar"><label className="search"><DropIcon className="search-icon" name="search" /><input placeholder="Поиск психолога, темы или подхода..." value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>section==="home"&&setSection("psychologists")}/></label><div className="top-actions"><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="icon-button" onClick={()=>{setSection("messages");notify(unread?`У вас ${unread} непрочитанных сообщения`:"Новых уведомлений нет")}} aria-label="Уведомления"><DropIcon className="top-drop" name="bell" />{unread>0&&<i/>}</motion.button><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="profile-chip" onClick={()=>setModal("profile")}>{avatar({photo:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",name:data.profile.name},"avatar sm")}<span>{data.profile.name}</span><span>⌄</span></motion.button></div></header>
      <div className="content-area"><AnimatePresence mode="wait" initial={false}><motion.div key={section} className="section-motion" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.32, ease: [0.22, 1, 0.36, 1] }}>
        {section==="home"&&<div className="dashboard-grid"><div className="main-column">
          <section className="hero"><div className="hero-copy"><span className="eyebrow">ПРОСТРАНСТВО ЗАБОТЫ О СЕБЕ</span><h1>Здесь тебя слышат</h1><p>Найди своего психолога и начни путь<br/>к внутреннему равновесию</p><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary" onClick={()=>setSection("psychologists")}>Подобрать психолога <span>→</span></motion.button></div><div className="hero-decor"><span>Маленькие шаги тоже приводят<br/>к большим переменам</span><b>♡</b></div><div className="hero-orb"/></section>
          <div className="specialty-row">{specialties.map((s,i)=><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} key={s} onClick={()=>{setSpecialty(s);setSection("psychologists")}} className="specialty"><DropIcon className={`specialty-icon color-${i}`} name={specialtyIcons[i]} /><span>{s}</span></motion.button>)}<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="specialty-next" onClick={()=>setSection("psychologists")}>›</motion.button></div>
          <div className="section-heading"><div><span className="eyebrow">ВАШИ СПЕЦИАЛИСТЫ</span><h2>Рекомендуемые психологи</h2></div><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="text-link" onClick={()=>setSection("psychologists")}>Смотреть все <b>→</b></motion.button></div>
          <div className="people-grid">{(data.psychologists.slice(0,4)).map(personCard)}</div>
          <section className="how"><div className="section-heading"><div><span className="eyebrow">ПОНЯТНО И БЕРЕЖНО</span><h2>Как это работает?</h2></div></div><div className="steps">{[["01","resource","Расскажите о своём запросе","Опишите, что вас беспокоит. Это поможет подобрать специалиста."],["02","search","Получите отклики","Психологи, которым близка ваша тема, откликнутся."],["03","person","Выберите психолога","Изучите профили, задайте вопросы и обсудите формат работы."],["04","calendar","Начните работу","Проводите сессии онлайн в удобное для вас время."]].map(s=><div className="step" key={s[0]}><div className="step-icon"><i>{s[0]}</i><DropIcon className="step-drop" name={s[1]} /></div><b>{s[2]}</b><p>{s[3]}</p></div>)}</div></section>
        </div><aside className="right-column"><section className="panel"><div className="panel-heading"><h2>Мои обращения</h2><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn small-btn primary" onClick={()=>setModal("request")}>＋ Новое</motion.button></div>{data.requests.slice(0,2).map(r=><article className="request-mini" key={r.id}><span className={`status ${r.status==="Закрыто"?"closed":"open"}`}>{r.status}</span><h3>{r.title}</h3><p>{r.description}</p><div className="request-meta"><span>▢ {r.replies} отклика</span><span>{r.status==="Открыто"?"2 дня назад":"12 мар."}</span></div></article>)}{!data.requests.length&&<p className="muted">Пока нет обращений</p>}<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="text-link block-link" onClick={()=>setSection("requests")}>Все обращения →</motion.button></section>
          <section className="panel"><div className="panel-heading"><h2>Ближайшие сессии</h2><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="text-link" onClick={()=>setSection("sessions")}>Все →</motion.button></div>{data.appointments.filter(a=>a.status==="Предстоит").slice(0,1).map(a=><div className="session-mini" key={a.id}><div className="person-line">{avatar(a,"avatar")}<div><b>{a.psychologist}</b><small>Онлайн-сессия</small></div></div><div className="session-detail">▦ &nbsp;{fmtDate(a.date)}, {a.time}</div><div className="session-detail">▣ &nbsp;Ссылка появится перед встречей</div><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn pale full" onClick={()=>setSection("sessions")}>Перейти к сессии</motion.button></div>)}</section>
          <section className="panel unread-panel"><div className="panel-heading"><h2>Непрочитанные</h2>{unread>0&&<span className="count-badge">{unread}</span>}</div>{data.psychologists.filter(p=>data.messages.some(m=>m.psychologist_id===p.id&&!m.mine&&!m.read)).slice(0,2).map(p=><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="message-preview" key={p.id} onClick={()=>openChat(p.id)}>{avatar(p,"avatar")}<span><b>{p.name}</b><small>{data.messages.filter(m=>m.psychologist_id===p.id).at(-1)?.body}</small></span><i>1</i></motion.button>)}<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="text-link block-link" onClick={()=>setSection("messages")}>Перейти в сообщения →</motion.button></section>
        </aside></div>}

        {section==="psychologists"&&<div className="page-content"><div className="page-title"><div><span className="eyebrow">ВАШ ПУТЬ НАЧИНАЕТСЯ ЗДЕСЬ</span><h1>Подобрать психолога</h1><p>Найдите специалиста, с которым будет комфортно</p></div></div><div className="filter-bar"><label className="search inline-search"><span>⌕</span><input placeholder="Имя, тема или специализация" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={specialty==="Избранное"?"":specialty} onChange={e=>setSpecialty(e.target.value)}><option value="">Все направления</option>{specialties.map(s=><option key={s}>{s}</option>)}</select><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={`filter-pill ${specialty==="Избранное"?"selected":""}`} onClick={()=>setSpecialty(specialty==="Избранное"?"":"Избранное")}>♡ Избранное {favorites.length>0&&`(${favorites.length})`}</motion.button></div><p className="result-count">{filteredPeople.length} психолога готовы помочь</p><div className="people-grid large">{filteredPeople.map(personCard)}</div>{!filteredPeople.length&&<div className="empty-state">По этому запросу никого не нашли. Попробуйте изменить фильтры.</div>}</div>}

        {section==="requests"&&<div className="page-content"><div className="page-title row-title"><div><span className="eyebrow">ВАШИ ТЕМЫ И ВОПРОСЫ</span><h1>Мои обращения</h1><p>Обсуждайте важное в своём темпе</p></div><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary" onClick={()=>setModal("request")}>＋ Новое обращение</motion.button></div><div className="request-list">{data.requests.map(r=><article className="request-card" key={r.id}><div className="request-head"><span className={`status ${r.status==="Закрыто"?"closed":"open"}`}>{r.status}</span><span className="muted small">{fmtDate(r.created_at.slice(0,10))}</span></div><h2>{r.title}</h2><p>{r.description}</p><div className="card-footer"><span>▢ &nbsp;{r.replies} специалиста откликнулись</span>{r.status==="Открыто"?<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="text-link" onClick={()=>action({action:"request-status",id:r.id,status:"Закрыто"},"PATCH")}>Закрыть обращение</motion.button>:<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="text-link" onClick={()=>action({action:"request-status",id:r.id,status:"Открыто"},"PATCH")}>Открыть снова</motion.button>}</div></article>)}{!data.requests.length&&<div className="empty-state">Пока нет обращений. Создайте первое — психологи помогут найти подходящий формат.</div>}</div></div>}

        {section==="sessions"&&<div className="page-content"><div className="page-title"><span className="eyebrow">ПЛАНИРУЙТЕ УДОБНО</span><h1>Мои сессии</h1><p>Все ваши встречи и договорённости в одном месте</p></div><div className="tabs"><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={filter==="Предстоящие"?"active":""} onClick={()=>setFilter("Предстоящие")}>Предстоящие</motion.button><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={filter==="Прошедшие"?"active":""} onClick={()=>setFilter("Прошедшие")}>Прошедшие</motion.button></div><div className="session-list">{data.appointments.filter(a=>filter==="Предстоящие"?a.status==="Предстоит":a.status!=="Предстоит").map(a=><article className="session-card" key={a.id}><div className="session-date"><b>{new Date(`${a.date}T12:00:00`).getDate()}</b><span>{new Intl.DateTimeFormat("ru-RU",{month:"short"}).format(new Date(`${a.date}T12:00:00`))}</span></div><div className="session-main"><div className="person-line">{avatar(a,"avatar lg-avatar")}<div><h2>{a.psychologist}</h2><span className="muted">{a.title}</span></div><span className={`status ${a.status==="Предстоит"?"open":"closed"}`}>{a.status}</span></div><div className="session-info"><span>◷ &nbsp;{a.time} · 50 минут</span><span>▣ &nbsp;{a.mode} (видеосвязь)</span><span>▤ &nbsp;Тема: {a.topic}</span></div><div className="session-actions">{a.status==="Предстоит"&&<><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary" onClick={()=>notify("Ссылка на видеосессию будет доступна незадолго до начала")}>▣ &nbsp;Перейти к сессии</motion.button><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn ghost" onClick={()=>action({action:"cancel-appointment",id:a.id},"PATCH")}>Отменить запись</motion.button></>}</div></div></article>)}{!data.appointments.some(a=>filter==="Предстоящие"?a.status==="Предстоит":a.status!=="Предстоит")&&<div className="empty-state">Здесь пока пусто. Подберите психолога и запишитесь на первую встречу.</div>}</div></div>}

        {section==="messages"&&<div className="page-content messages-page"><div className="page-title"><span className="eyebrow">ВАШЕ ПРОСТРАНСТВО ДИАЛОГА</span><h1>Сообщения</h1></div><div className="chat-layout"><aside className="thread-list">{data.psychologists.filter(p=>data.messages.some(m=>m.psychologist_id===p.id)).map(p=>{const last=data.messages.filter(m=>m.psychologist_id===p.id).at(-1)!;return <motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={`thread ${conversation===p.id?"active":""}`} key={p.id} onClick={()=>openChat(p.id)}>{avatar(p,"avatar")}<span><b>{p.name}</b><small>{last.body}</small></span><time>{last.created_at.slice(11,16)}</time>{data.messages.some(m=>m.psychologist_id===p.id&&!m.mine&&!m.read)&&<i className="unread-dot"/>}</motion.button>})}</aside><section className="chat-window">{conversation===null?<div className="chat-empty"><span>♡</span><h2>Выберите диалог</h2><p>Ваши сообщения с психологами появятся здесь</p></div>:<><div className="chat-head">{avatar(data.psychologists.find(p=>p.id===conversation)!,"avatar")}<div><b>{data.psychologists.find(p=>p.id===conversation)?.name}</b><small><i/> Онлайн</small></div><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} onClick={()=>setSection("sessions")}>▣</motion.button></div><div className="chat-body">{data.messages.filter(m=>m.psychologist_id===conversation).map(m=><div className={`bubble-row ${m.mine?"mine":""}`} key={m.id}>{!m.mine&&avatar(data.psychologists.find(p=>p.id===conversation)!,"avatar tiny")}<div className="bubble">{m.body}<time>{m.created_at.slice(11,16)} {m.mine&&"✓✓"}</time></div></div>)}</div><form className="chat-form" onSubmit={sendMessage}><input value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Напишите сообщение..."/><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="send-btn" disabled={busy||!chatText.trim()}>➤</motion.button></form></>}</section></div></div>}

        {section==="resources"&&<div className="page-content"><div className="page-title"><span className="eyebrow">МЯГКО И В СВОЁМ ТЕМПЕ</span><h1>Полезные материалы</h1><p>Небольшие практики и знания для заботы о себе</p></div><div className="resource-grid">{data.resources.map(r=><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="resource-card" key={r.id} onClick={()=>setResource(r)}><div className={`resource-art ${r.color}`}><DropIcon className="resource-drop" name={r.color==="sage"?"leaf":r.color==="sand"?"sparkle":r.color==="rose"?"heart":"cloud"} /><i>✧</i></div><div className="resource-copy"><span className="eyebrow">{r.category} · {r.read_time}</span><h2>{r.title}</h2><p>{r.description}</p><span className="text-link">Открыть материал →</span></div></motion.button>)}</div></div>}

        {section==="community"&&<div className="page-content"><div className="page-title"><span className="eyebrow">ВМЕСТЕ ЧУТЬ ЛЕГЧЕ</span><h1>Сообщество</h1><p>Здесь можно почувствовать, что вы не одни</p></div><div className="community-card"><span className="community-art">☼</span><h2>Бережное пространство рядом</h2><p>Сейчас мы готовим безопасные группы поддержки и встречи с психологами. А пока вы можете поделиться своей темой в обращении — специалисты откликнутся лично.</p><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary" onClick={()=>setModal("request")}>Создать обращение</motion.button></div></div>}

        {section==="about"&&<div className="page-content"><div className="page-title"><span className="eyebrow">MINDPLACE · ЗАБОТА РЯДОМ</span><h1>О сервисе</h1><p>Пространство, где можно быть собой</p></div><div className="about-card"><div className="brand-mark large-mark"><span>◕</span><span>◕</span></div><h2>Поддержка начинается с разговора</h2><p>MindPlace помогает найти своего психолога, бережно рассказать о том, что вас волнует, и начать работу в комфортном темпе.</p><div className="about-points"><span>✦ Проверенные специалисты</span><span>✦ Удобные онлайн-сессии</span><span>✦ Безопасное пространство</span></div><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary" onClick={()=>setSection("psychologists")}>Найти психолога</motion.button></div></div>}
      </motion.div></AnimatePresence></div>
    </section>

    <nav className="mobile-nav">{menus.slice(0,5).map(([id,label,icon])=><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className={section===id?"active":""} key={id} onClick={()=>setSection(id)}><DropIcon className="mobile-drop" name={icon} /><small>{id==="psychologists"?"Психологи":label.replace("Мои ","")}</small></motion.button>)}</nav>
    {<AnimatePresence>{modal&&<motion.div key="dialog" className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.22 }} onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><motion.form className="modal" onSubmit={submit} initial={{ opacity: 0, y: 18, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8, scale: 0.985 }} transition={{ type: "spring", stiffness: 260, damping: 28 }}><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} type="button" className="modal-close" onClick={()=>setModal(null)}>×</motion.button><span className="eyebrow">{modal==="request"?"ВАШ ЗАПРОС":modal==="booking"?"ПЕРВАЯ ВСТРЕЧА":"ЛИЧНЫЕ ДАННЫЕ"}</span><h2>{modal==="request"?"Новое обращение":modal==="booking"?"Записаться на сессию":"Мой профиль"}<small>{modal==="request"?"Расскажите, что вас волнует. Вы сами решаете, чем делиться.":modal==="booking"?"Выберите удобное время для встречи.":"Эти данные видны только вам."}</small></h2>{modal==="request"?<><label>Тема обращения<input name="title" placeholder="Например, тревога и выгорание" required/></label><label>Что вас беспокоит?<textarea name="description" rows={4} placeholder="Расскажите немного о своей ситуации..." required/></label></>:modal==="booking"?<><label>Психолог<select name="psychologistId" value={chosen??selectedPerson?.id??""} onChange={e=>setChosen(Number(e.target.value))}>{data.psychologists.map(p=><option value={p.id} key={p.id}>{p.name} · {p.title}</option>)}</select></label><div className="form-row"><label>Дата<input type="date" name="date" min={new Date().toISOString().slice(0,10)} defaultValue={new Date(Date.now()+86400000).toISOString().slice(0,10)} required/></label><label>Время<select name="time"><option>10:00</option><option>12:30</option><option>15:00</option><option>18:00</option><option>19:00</option></select></label></div><label>Тема встречи<input name="topic" placeholder="Что хотели бы обсудить?"/></label><p className="form-hint">Онлайн-встреча · 50 минут · 2 500 ₽</p></>:<><label>Имя<input name="name" defaultValue={data.profile.name} required/></label><label>Электронная почта<input name="email" type="email" defaultValue={data.profile.email} placeholder="name@example.com"/></label></>}<motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary full modal-submit" disabled={busy}>{busy?"Сохраняем…":modal==="request"?"Отправить обращение":modal==="booking"?"Подтвердить запись":"Сохранить изменения"}</motion.button></motion.form></motion.div>}</AnimatePresence>
    {resource&&<AnimatePresence><motion.div key="resource" className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.22 }} onMouseDown={e=>e.target===e.currentTarget&&setResource(null)}><motion.article className="modal resource-modal" initial={{ opacity: 0, y: 18, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8, scale: 0.985 }} transition={{ type: "spring", stiffness: 260, damping: 28 }}><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="modal-close" onClick={()=>setResource(null)}>×</motion.button><div className={`resource-art ${resource.color}`}><DropIcon className="resource-drop" name={resource.color==="sage"?"leaf":resource.color==="sand"?"sparkle":resource.color==="rose"?"heart":"cloud"} /><i>✧</i></div><span className="eyebrow">{resource.category} · {resource.read_time}</span><h2>{resource.title}</h2><p>{resource.description}</p><p>Попробуйте выделить для себя несколько минут в спокойном месте. Сделайте медленный вдох и обратите внимание на то, что происходит внутри — без оценки и спешки. Поддержка начинается с маленького шага.</p><motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }} transition={{ type: "spring", stiffness: 360, damping: 28 }} className="btn primary full" onClick={()=>setResource(null)}>Понятно</motion.button></motion.article></motion.div></AnimatePresence>}
    <AnimatePresence>{notice&&<motion.div className="toast" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 10 }} transition={{ type: "spring", stiffness: 300, damping: 28 }}>✓ &nbsp;{notice}</motion.div>}</AnimatePresence>{loading&&<motion.div className="loading-bar" initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: 0.45, ease: "easeOut" }}/>}
  </main></MotionConfig>;
}
