create table if not exists public.psychologists (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null,
  rating numeric(2,1) not null check (rating between 0 and 5),
  reviews integer not null default 0 check (reviews >= 0),
  experience text not null,
  tags text[] not null default '{}',
  photo text not null,
  availability text not null default 'Сегодня'
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  status text not null default 'Открыто' check (status in ('Открыто', 'Закрыто')),
  created_at timestamptz not null default now(),
  replies integer not null default 0 check (replies >= 0)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  psychologist_id bigint not null references public.psychologists(id),
  date date not null,
  time time not null,
  topic text not null,
  mode text not null default 'Онлайн',
  status text not null default 'Предстоит' check (status in ('Предстоит', 'Прошла', 'Отменена')),
  created_at timestamptz not null default now()
);
create unique index if not exists appointments_unique_active_slot
  on public.appointments (psychologist_id, date, time) where status = 'Предстоит';

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  psychologist_id bigint not null references public.psychologists(id),
  body text not null,
  mine boolean not null default false,
  created_at timestamptz not null default now(),
  read boolean not null default false
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  read_time text not null,
  color text not null,
  icon text not null,
  description text not null
);

create table if not exists public.profile (
  id smallint primary key check (id = 1),
  name text not null,
  email text not null default ''
);

alter table public.psychologists enable row level security;
alter table public.requests enable row level security;
alter table public.appointments enable row level security;
alter table public.messages enable row level security;
alter table public.resources enable row level security;
alter table public.profile enable row level security;

insert into public.psychologists (id,name,title,rating,reviews,experience,tags,photo,availability) values
  (1,'Анна Крылова','Клинический психолог',5.0,32,'8 лет',array['Тревога','Самооценка','Отношения'],'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=85','Сегодня'),
  (2,'Игорь Лебедев','Гештальт-терапевт',4.9,27,'12 лет',array['Кризисные ситуации','Поиск себя','Самооценка'],'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=85','Завтра'),
  (3,'Мария Соколова','КПТ-терапевт',4.8,41,'6 лет',array['Тревога','Депрессия','Панические атаки'],'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&q=85','Сегодня'),
  (4,'Даниил Морозов','Семейный психолог',4.9,30,'10 лет',array['Отношения','Семейные кризисы','Родительство'],'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=240&q=85','Сегодня'),
  (5,'Елена Смирнова','Психоаналитик',4.7,19,'9 лет',array['Потеря смысла','Апатия','Самооценка'],'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=240&q=85','Завтра')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.psychologists','id'), greatest((select max(id) from public.psychologists), 1));

insert into public.requests (id,title,description,status,replies,created_at) values
  (1,'Тревога и выгорание','Постоянное чувство тревоги, сложно справляться с нагрузкой на работе…','Открыто',3,now()-interval '2 days'),
  (2,'Сложности в отношениях','Конфликты с партнёром, не понимаю, как выстроить диалог','Закрыто',5,now()-interval '16 days')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.requests','id'), greatest((select max(id) from public.requests), 1));

insert into public.appointments (id,psychologist_id,date,time,topic,mode,status) values
  (1,1,current_date+1,'18:00','Тревога и самокритика','Онлайн','Предстоит'),
  (2,2,current_date+4,'12:30','Самооценка и поиск себя','Онлайн','Предстоит')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.appointments','id'), greatest((select max(id) from public.appointments), 1));

insert into public.messages (id,psychologist_id,body,mine,created_at,read) values
  (1,1,'Спасибо за ваше обращение. Предлагаю созвониться и обсудить ваш запрос подробнее. Когда вам будет удобно?',false,now()-interval '1 day',true),
  (2,1,'Здравствуйте! Спасибо! Мне удобно в среду после 18:00. Это возможно?',true,now()-interval '1 day'+interval '3 minutes',true),
  (3,1,'Да, среда в 18:00 подойдёт. Я отправлю вам ссылку на сессию и несколько вопросов, чтобы лучше подготовиться 🌿',false,now()-interval '1 day'+interval '5 minutes',false),
  (4,2,'Хорошо, давайте перенесём на завтра. Увидимся!',false,now()-interval '2 days',true),
  (5,3,'Здравствуйте! Готова взять вас в работу. Расскажите подробнее, что вас беспокоит.',false,now()-interval '3 days',false)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.messages','id'), greatest((select max(id) from public.messages), 1));

insert into public.resources (id,title,category,read_time,color,icon,description) values
  (1,'Как справляться с тревогой','Статьи','5 мин','sage','✿','Практические техники, которые помогут снизить тревожность и вернуть ощущение опоры.'),
  (2,'Практика осознанности','Упражнение','3 мин','sand','☼','Короткая практика, чтобы замедлиться и вернуться в настоящий момент.'),
  (3,'Эмоциональные границы','Статьи','6 мин','rose','♡','Как замечать свои границы, говорить о них и бережно поддерживать себя.'),
  (4,'Дневник настроения','Практика','4 мин','blue','☁','Простое упражнение для внимательного наблюдения за своими чувствами.')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.resources','id'), greatest((select max(id) from public.resources), 1));

insert into public.profile (id,name,email) values (1,'Алексей','alexey@example.com') on conflict (id) do nothing;
